In [1]:
import datetime as dt
import re
from datetime import date
import pandas as pd

def calc_rate(cost, symbol_to):
    if not symbol_to.strip():
        return
    symbolOp = re.split(r'([\d.]+)', symbol_to)
    final_value = float(symbolOp[3])
    final_date = dt.datetime.strptime(str(int(symbolOp[1])), '%y%m%d').date()
    days_hold = (final_date - date.today()).days
    rate_of_gain = float(cost) / final_value * (365 / days_hold) * 100
    return symbol_to + " " + str(round(rate_of_gain))

df = pd.read_csv('G:\My Drive\data\out_fidelity.csv')
df = df.dropna(subset=['TEMA_seq'])
df = df[(df['gainLoss'] == 'sell') | (df['gainLoss'] == 'buy')]
for i in df.index:
    try:
        df.loc[i, 'comments'] = calc_rate(df['pct'][i], df['TEMA_seq'][i])
    except Exception as e:
        print(i, e)
df[['Account', 'Symbol', 'sell', 'pct', 'comments', 'gainLoss']]

      Account          Symbol   sell   pct            comments gainLoss
23  218320885  COST251121P915  27.35  11.1    DHI251121P160 70     sell
29  218320885  CRON251017C2.5   0.35  0.35    CRON251121C3 118     sell
37  218320886  DUOL251121C320  39.80  41.5  DUOL251128C345 102     sell

In [10]:
def roll_gain(symbol_from, symbol_to, diff):
    symbolOp = re.split(r'([\d.]+)', symbol_from)
    initial_value = float(symbolOp[3])
    symbolOp = re.split(r'([\d.]+)', symbol_to)
    final_value = float(symbolOp[3])
    final_date = dt.datetime.strptime(str(int(symbolOp[1])), '%y%m%d').date()
    days_hold = (final_date - date.today()).days
    rate_of_gain = (final_value - initial_value + float(diff)) / initial_value * (365 / days_hold) * 100
    return str(round(rate_of_gain))

df = pd.read_csv('G:\My Drive\data\out_fidelity.csv')
df = df[(df['gainLoss'] == 'roll')]

for i in df.index:
    try:
        df.loc[i, 'comments'] = roll_gain(df['Symbol'][i], df['TEMA_seq'][i], df['pct'][i])
    except Exception as e:
        print(i, e)
df[['Account', 'Symbol', 'sell', 'pct', 'TEMA_seq', 'comments']]

Empty DataFrame
Columns: [Account, Symbol, sell, pct, TEMA_seq, comments]
Index: []

In [3]:
print(calc_rate('COST800',31.75))
print(calc_rate('XOM115',4.95))
print(calc_rate('MSFT395',17.8))
print(calc_rate('ISRG440',21))
print(calc_rate('GOOGL160',8.35))
print(calc_rate('AAPL210',11.35))
print(calc_rate('MU103',5.5))
print(calc_rate('AMZN165',10.5))
print(calc_rate('ABNB125',9.35))
print(calc_rate('SQ57.5',4.6))
print(calc_rate('LVS40',3.35))
print(calc_rate('TSLA200',18.1))
print(calc_rate('CCL15',1.4))
print(calc_rate('CRWD230',25.45))
print(calc_rate('NVDA100',11.3))
print(calc_rate('SMCI620',77.5))
print(calc_rate('COIN195',25))
print(calc_rate('TQQQ54',7.55))
print(calc_rate('MSTR1320',200.6))
print(calc_rate('NNOX7.5',1.3))
print(calc_rate('SOXL28',6.3))
print(calc_rate('DJT27.5',6.8))

AttributeError: 'float' object has no attribute 'strip'

In [ ]:
roll_gain('UAL240315C39', 4.9, 5.1, 'UAL240419C40')

In [9]:
def calculate_rate_of_gain(initial_value, final_value, symbol):
    symbolOp = re.split(r'([\d.]+)', symbol)
    myDate = dt.datetime.strptime(str(int(symbolOp[1])), '%y%m%d').date()
    days_hold = (myDate - date.today()).days
    rate_of_gain = (final_value - initial_value) / initial_value * (365 / days_hold) * 100
    return round(rate_of_gain)

calculate_rate_of_gain(100, 110, 'MSTR240419C940')

-7

In [55]:
def calculate_rate_of_gain(initial_value, final_value, days_hold):
    rate_of_gain = (final_value - initial_value) / initial_value * (365 / days_hold) * 100
    return round(rate_of_gain, 1)

calculate_rate_of_gain(100, 110, 30)

121.7