In [1]:
import datetime as dt
import re
from datetime import date

import pandas as pd
import yfinance as yf
pd.options.mode.chained_assignment = None  # default='warn'
pd.set_option('display.width', 1000)  # display all columns without wrapping
pd.set_option('display.max_columns', None)  # display all columns
pd.set_option('display.max_rows', None)  # display all rows

def calc_rate(cost, symbol_to):
    if not symbol_to.strip():
        return
    symbolOp = re.split(r'([\d.]+)', symbol_to)
    final_value = float(symbolOp[3])
    final_date = dt.datetime.strptime(str(int(symbolOp[1])), '%y%m%d').date()
    days_hold = (final_date - date.today()).days
    rate_of_gain = float(cost) / final_value * (365 / days_hold) * 100
    return round(rate_of_gain)

In [2]:
def _scan_P(df):
    for i in df.index:
        try:
            symbolOp = re.split(r'([\d.]+)', df['Symbol'][i])
            tk = yf.Ticker(symbolOp[0])

            myDate = dt.datetime.strptime(str(int(symbolOp[1])), '%y%m%d').date()
            symbolOp[1] = myDate.strftime('%Y-%m-%d')

            optC = tk.option_chain(symbolOp[1])
            opt = optC.puts
            opt = opt[ (opt['strike'] - float(symbolOp[3])).abs() < 1 ]
            df.loc[i,'buy'] = pd.Series(opt['bid']).values[0]            
            sell = float(df['sell'][i])
            df.loc[i,'gainLoss'] = (df['buy'][i] - sell) * df['Quantity'][i]
            df.loc[i,'pct'] = round(df['gainLoss'][i] * 100 / sell / abs(df['Quantity'][i]))
            df.loc[i, 'comments'] = calc_rate(df['buy'][i], df['Symbol'][i])
        except Exception as e:
            print(symbolOp[0],e)
    return df[['Account', 'Symbol', 'buy', 'sell', 'gainLoss', 'pct', 'comments']]

In [6]:
# 01:05
df = pd.read_csv('G:\My Drive\data\out_fidelity.csv')
df = df[(df['Option'] == 'P')]
df_P = _scan_P(df)
df_P = df_P.sort_values(by=['pct'], ascending=False)
df_P.reset_index(drop=True)

BRKB Expiration `2025-11-21` cannot be found. Available expirations are: []

      Account            Symbol    buy   sell gainLoss   pct comments
0   218320886    AMZN251121P220   0.30   12.9     25.2    98        5
1   X83939133    NVDA251114P185   0.89    6.3     5.41    86       44
2   X83939133  NVDA251114P187.5   1.29   5.15     3.86    75       63
3   218320885    NUGT251121P135   3.90   14.8     10.9    74       96
4   X83939133     UBER251114P94   2.03    4.8     2.77    58      197
5   X83939133  NVDA251114P192.5   2.60   6.15     3.55    58      123
6   218320885   NFLX251121P1100  14.20  32.15    17.95    56       43
7   218320885    COST251121P915  13.55  27.35     13.8    50       49
8   X83939133     AMD251114P240   4.70   9.45     4.75    50      179
9   218320885   NFLX251121P1115  19.80     36     16.2    45       59
10  X83939133    TSLA251114P445  12.40  19.35     6.95    36      254
11  218320885   NFLX251121P1145  36.05   40.7     4.65    11      104
12  218320886    COIN251121P350  34.35   31.6    -2.75    -9      326
13  218320885   QUBT251121P16.5   2.75   2.45     -0.3   -12      553
14  218320885    CRWV251121P124  18.75   14.3    -4.45   -31      502
15  218320885    META251121P660  31.60     24     -7.6   -32      159
16  218320885     HIMS251121P51   9.10   6.85    -2.25   -33      592
17  X83939133  MSTR251121P282.5  41.25   22.8   -18.45   -81      485
18  X83939133  MSFT251114P527.5  22.10    9.7    -12.4  -128      382
19  218320885  BRKB251121P477.5    NaN   8.15      NaN   NaN      NaN

In [4]:
def _scan_C(df):
    for i in df.index:
        try:
            symbolOp = re.split(r'([\d.]+)', df['Symbol'][i])
            tk = yf.Ticker(symbolOp[0])

            myDate = dt.datetime.strptime(str(int(symbolOp[1])), '%y%m%d').date()
            symbolOp[1] = myDate.strftime('%Y-%m-%d')

            optC = tk.option_chain(symbolOp[1])
            opt = optC.calls
            opt = opt[(opt['strike'] == float(symbolOp[3]))]

            df.loc[i, 'buy'] = pd.Series(opt['bid']).values[0]
            sell = float(df['sell'][i])
            df.loc[i, 'gainLoss'] = sell - df['buy'][i]
            df.loc[i, 'pct'] = round(df['gainLoss'][i] * 100 / sell)
            df.loc[i, 'comments'] = calc_rate(df['buy'][i], df['Symbol'][i])
            # with contextlib.redirect_stdout(io.StringIO()):
            #     df_yh = yf.download(symbolOp[0], period="20d", interval="1h")
            # row = _MA_screen(df_yh, 20)
            # df['TEMA_seq'][i] = row[0]
            # if ((df['pct'][i] > 0) & (float(df['TEMA_seq'][i]) > 0)):
            #     df['Option'][i] = 'buy C'
        except Exception as e:
            print(symbolOp[0],e)
    return df[['Account', 'Symbol', 'buy', 'sell', 'gainLoss', 'pct', 'comments']]

In [5]:
df = pd.read_csv('G:\My Drive\data\out_fidelity.csv')
df = df[(df['Option'] == 'C')]
df_C = _scan_C(df)
df_C = df_C.sort_values(by=['pct'], ascending=False)
df_C.reset_index(drop=True)

COST expected string or bytes-like object

      Account            Symbol  buy              sell gainLoss  pct comments
0   X65750304    AAPL251121C220  0.0              6.81     6.81  100        0
1   X83939133     AMD251121C210  0.0             20.20     20.2  100        0
2   X83939133   UBER251121C92.5  0.0              10.5     10.5  100        0
3   218320885    TTD251121C47.5  0.0               5.6      5.6  100        0
4   X83939133    TSLA251121C350  0.0               5.8      5.8  100        0
5   X83939133     SMCI251121C55  0.0              5.75     5.75  100        0
6   231736622     SMCI251121C47  0.0               5.6      5.6  100        0
7   X83939133    NVDA251219C100  0.0               7.2      7.2  100        0
8   X83939133    NVDA251121C185  0.0              17.5     17.5  100        0
9   X83939133    NVDA251121C180  0.0             15.03    15.03  100        0
10  X83939133  MSTR251121C302.5  0.0             23.55    23.55  100        0
11  X83939133    MSTR251121C300  0.0                25     25.0  100        0
12  X83939133  MSFT251121C522.5  0.0              18.4     18.4  100        0
13  218320885        LC260116C7  0.0              2.98     2.98  100        0
14  218320886    DUOL251121C320  0.0              39.8     39.8  100        0
15  218320885    COST251121C960  0.0                28     28.0  100        0
16  218320886    COST251121C945  0.0              27.8     27.8  100        0
17  218320886     COIN251219C80  0.0             33.55    33.55  100        0
18  X65750304    COIN251121C365  0.0             27.75    27.75  100        0
19  X65750304    COIN251121C360  0.0             26.35    26.35  100        0
20  X65750304    COIN251121C355  0.0              27.5     27.5  100        0
21  X65750304    COIN251121C345  0.0             26.35    26.35  100        0
22  X65750304    ASML260116C830  0.0               0.1      0.1  100        0
23  X65750304    ASML251121C760  0.0               4.5      4.5  100        0
24  218320885      AMD251219C90  0.0              6.92     6.92  100        0
25  X83939133     UBER251121C97  0.0               4.9      4.9  100        0
26  218320885               NaN  NaN  0.35CRON251121C3      NaN  NaN      NaN

In [ ]:
def _MA_screen(df, x):
    df['SMA'] = round(df['Adj Close'].rolling(window=x).mean(), 2)  # Simple Moving Average

    # TEMA triple exponential moving average | EMA Exponential Moving Average
    df['EMA1'] = round(df['Adj Close'].ewm(span=x, adjust=False).mean(), 2)
    df['EMA2'] = round(df['EMA1'].ewm(span=x, adjust=False).mean(), 2)
    df['EMA3'] = round(df['EMA2'].ewm(span=x, adjust=False).mean(), 2)
    df['TEMA'] = 3 * (df['EMA1'] - df['EMA2']) + df['EMA3']

    # up/down from previous 2 days
    df['SMA_2'] = df.SMA.shift(2)
    df['TEMA_2'] = df.TEMA.shift(2)
    df['SMA_up'] = df.apply(lambda x: '+' if x['SMA'] >= x['SMA_2'] else '-', axis=1)
    df['TEMA_up'] = df.apply(lambda x: '+' if x['TEMA'] >= x['TEMA_2'] else '-', axis=1)

    # reverse up/down
    df['SMA_up_1'] = df.SMA_up.shift(1)
    df['TEMA_up_1'] = df.TEMA_up.shift(1)
    df = df.dropna(subset=['SMA', 'SMA_2', 'TEMA', 'TEMA_2', 'SMA_up_1', 'TEMA_up_1'])
    df['SMA_up_rev'] = df.apply(lambda x: x['SMA_up'] if x['SMA_up'] != x['SMA_up_1'] else '', axis=1)
    df['TEMA_up_rev'] = df.apply(lambda x: x['TEMA_up'] if x['TEMA_up'] != x['TEMA_up_1'] else '', axis=1)

    SMA_seq = ''
    TEMA_seq = ''
    seq = 0
    for i in df.index[::-1]:  # look backwards
        seq += 1
        if bool(SMA_seq) & bool(TEMA_seq):
            break
        if (not SMA_seq) & bool(df['SMA_up_rev'][i]):
            SMA_seq = df['SMA_up_rev'][i] + str(seq)
        if (not TEMA_seq) & bool(df['TEMA_up_rev'][i]):
            TEMA_seq = df['TEMA_up_rev'][i] + str(seq)
    return [TEMA_seq, SMA_seq]

In [7]:
def rsi(df, periods=14, ema=True):
    close_delta = df['Adj Close'].diff()

    # Make two series: one for lower closes and one for higher closes
    up = close_delta.clip(lower=0)
    down = -1 * close_delta.clip(upper=0)

    if ema == True:
        # Use exponential moving average
        ma_up = up.ewm(com=periods - 1, adjust=True, min_periods=periods).mean()
        ma_down = down.ewm(com=periods - 1, adjust=True, min_periods=periods).mean()
    else:
        # Use simple moving average
        ma_up = up.rolling(window=periods, adjust=False).mean()
        ma_down = down.rolling(window=periods, adjust=False).mean()

    rsi = ma_up / ma_down
    rsi = 100 - (100 / (1 + rsi))
    return round(rsi[-1])

In [ ]:
import contextlib
import io

import pandas as pd
import yfinance as yf

yf.pdr_override()
pd.options.mode.chained_assignment = None  # default='warn'

def _MA_screen_list(stockList, x):
    stockList = list(set(stockList))  # make elements unique
    stockList = sorted(stockList)
    rows = []
    for symbol in stockList:
        try:
            with contextlib.redirect_stdout(io.StringIO()):
                #df_yh = yf.download(symbol, period="120d")
                df_yh = yf.download(symbol, period="20d", interval="1h")
            row = _MA_screen(df_yh, x)
            row.append(rsi(df_yh))
            row.append(symbol)
            rows.append(row)
        except Exception:
            print(symbol)
    out_df = pd.DataFrame(rows, columns=['TEMA_seq', 'SMA_seq', 'RSI', 'symbol'])

    out_df.TEMA_seq = out_df.TEMA_seq.astype(float)
    out_df.SMA_seq = out_df.SMA_seq.astype(float)
    out_df = out_df.sort_values(by=['RSI', 'TEMA_seq', 'SMA_seq'], ascending=False)
    return out_df

In [ ]:
import pandas as pd

df = pd.read_csv('G:\My Drive\data\out_fidelity.csv')
df = df[(df['C2'].notnull())]
stockList = df['Ticker'].tolist()

_MA_screen_list(stockList, 20)

In [ ]:
df_P.sort_values(by=['buy'])

In [ ]:
# -1 reverse down to buy to close P or sell C | 0:00:17 
import pandas as pd

df = pd.read_csv('G:\My Drive\data\out_fidelity.csv')
df = df[(df['Option'] == 'P') | (df['C2'].notnull())] 
stockList = df['Ticker'].tolist()

_MA_screen_list(stockList, 20)

In [ ]:
# +1 reverse up: buy to close C
import pandas as pd

df = pd.read_csv('G:\My Drive\data\out_fidelity.csv')
df = df[(df['Option'] == 'C')] 
stockList = df['Ticker'].tolist()

_MA_screen_list(stockList, 20)

In [ ]:
import datetime as dt

def _pickUpDn(limitDay, filename):
    out_df = pd.read_csv(DIR + filename)
    today = dt.datetime.now().strftime('%d')
    upList = out_df[(0 <= out_df['TEMA_seq']) & (out_df['TEMA_seq'] <= limitDay)]  # & (out_df['SMA_seq'] < -9)
    print(upList)
    upList['symbol'].to_csv('..\data\out_PythonRevUp' + today + '.txt', index=False, header=False)

    dnList = out_df[(-limitDay <= out_df['TEMA_seq']) & (out_df['TEMA_seq'] <= 0)]  # & (out_df['SMA_seq'] > 9)
    print(dnList)
    dnList['symbol'].to_csv('..\data\out_PythonRevDn' + today + '.txt', index=False, header=False)

In [ ]:
_pickUpDn(3, '\out_Python_MA_SP.csv')

In [ ]:
# Scan yuanjing list
df = pd.read_csv(r'E:\pythonProject\data\in_stockList.csv', sep='[";"]', engine='python')
stockList = []
for i in df.index:
    symbolList = df['Symbol'][i]
    for x in symbolList.split(','):
        stockList.append(x.split(':')[-1])
        
out_df = _MA_screen_list(stockList, 20)
out_df[(1 <= out_df['TEMA_seq']) & (out_df['SMA_seq'] <= 0)] # reverse up, sell P

In [ ]:
import datetime as dt
import re

import pandas as pd
import yfinance as yf

pd.options.mode.chained_assignment = None  # default='warn'

def _scan_C(df):
    for i in df.index:
        try:
            symbolOp = re.split(r'([\d.]+)', df['Symbol'][i])
            tk = yf.Ticker(symbolOp[0])

            myDate = dt.datetime.strptime(str(int(symbolOp[1])), '%y%m%d').date()
            symbolOp[1] = myDate.strftime('%Y-%m-%d')

            optC = tk.option_chain(symbolOp[1])
            opt = optC.calls
            opt = opt[(opt['strike'] == float(symbolOp[3]))]

            df['buy'][i] = pd.Series(opt['bid']).values[0]
            sell = float(df['sell'][i])
            df['gainLoss'][i] = sell - df['buy'][i]
            df['pct'][i] = round(df['gainLoss'][i] * 100 / sell)
        except Exception:
            print(symbolOp[0])
    return df[['Account', 'Symbol', 'buy', 'sell', 'gainLoss', 'pct', 'Option']]

In [40]:
# test
symbolOp = re.split(r'([\d.]+)', 'MSTR251121P282.5')
print(symbolOp)
tk = yf.Ticker(symbolOp[0])
myDate = dt.datetime.strptime(str(int(symbolOp[1])), '%y%m%d').date()
symbolOp[1] = myDate.strftime('%Y-%m-%d')
optC = tk.option_chain(symbolOp[1])
#print(optC)
opt = optC.puts
opt = opt[ (opt['strike'] - float(symbolOp[3])).abs() < 3 ]
print(opt)

['MSTR', '251121', 'P', '282.5', '']
         contractSymbol             lastTradeDate  strike  lastPrice   bid    ask    change  percentChange  volume  openInterest  impliedVolatility  inTheMoney contractSize currency
24  MSTR251121P00280000 2025-10-24 14:39:56+00:00   280.0      14.55  15.2  15.80 -3.650001     -20.054947   217.0          5672           0.634220       False      REGULAR      USD
25  MSTR251121P00285000 2025-10-24 14:54:36+00:00   285.0      18.30  17.6  18.35 -1.900001      -9.405948     5.0           573           0.637577       False      REGULAR      USD